### ISSUE TITLE
Where to "put" the init() function

### ISSUE THREAD

**Issue by jbelien** [Tigerman55/SentryDelegator#1]
I came here following my question here: https://discourse.zendframework.com/t/sentry-io-integration-in-expressive/1155

--- 

That looks (almost exactly) to what I was coding based on outdated libraries.
I just put the `Sentry\init()` function in the `__invoke()` function of my listener (your `ErrorListener`).

Is there a reason **not** to put the `Sentry\init()` function there ?

**Comment by Tigerman55** [comment]
One reason I put it within `ConfigureSentry()` is to bind environment or other options to `Sentry\init()`. We only want the `Sentry\init()` function to be run exactly once, and we need access to the application config. I considered putting it in a factory of some kind, but that breaks class responsibility in my opinion.
